title: Revealing Octocats
description: Publish reveal.js slides with jekyll on GitHub Pages
#theme: jekyll-theme-cayman
theme: jekyll-theme-hacker
show_downloads: false
google_analytics:

timezone: Europe/Berlin
locale: en_US
encoding: UTF-8

# Has to be explicit as long as https://github.com/jekyll/jekyll/issues/4791 is not fixed
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - reveal.js/bower.json
    - reveal.js/CONTRIBUTING.md
    - reveal.js/demo.html
    - reveal.js/Gruntfile.js
    - reveal.js/index.html
    - reveal.js/LICENSE
    - reveal.js/node_modules
    - reveal.js/package.json
    - reveal.js/README.md
    - reveal.js/test
include: 
    - reveal.js/css
    - reveal.js/js
    - reveal.js/lib
    - reveal.js/plugin

# Does not work as long as https://github.com/jekyll/jekyll/issues/6209 and https://github.com/jekyll/jekyll/issues/6211 are not fixed
#collections:
#    slides:
#        output: true
#        permalink: /:collection/:path

defaults:
    - scope:
        path: "slides"
      values:
        layout: slide
    - scope:
        type: slides
      values:
        layout: slide

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

safe: true
strict_front_matter: true
